server:
  port: 8585

spring:
  application:
    name: Pagination

  datasource:
    url: jdbc:h2:mem:pagination;Mode=Oracle
    platform: h2
    enable: true
    path: h2-console

  #access h2: localhost:8585/h2-console
  #url: jdbc:h2:mem:pagination
  #add devtool dependency to pom
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update